// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxsgW_rlKFFjlaGeFNqWMmDRPpgY8Gt1s',
    appId: '1:434342175035:web:bb376da13821e4cb6ad71e',
    messagingSenderId: '434342175035',
    projectId: 'food-management-app-84f29',
    authDomain: 'food-management-app-84f29.firebaseapp.com',
    storageBucket: 'food-management-app-84f29.appspot.com',
    measurementId: 'G-KX26NCWBFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6-F9mhXXAhy-BBbtQQSGs9uiFjJYjhUc',
    appId: '1:434342175035:android:e6b2a7f3cbfe1dcb6ad71e',
    messagingSenderId: '434342175035',
    projectId: 'food-management-app-84f29',
    storageBucket: 'food-management-app-84f29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARGQpBepj292_z8wd7nXEbW8J0jPitTbw',
    appId: '1:434342175035:ios:9d4f961de97168a86ad71e',
    messagingSenderId: '434342175035',
    projectId: 'food-management-app-84f29',
    storageBucket: 'food-management-app-84f29.appspot.com',
    iosBundleId: 'com.example.foodManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARGQpBepj292_z8wd7nXEbW8J0jPitTbw',
    appId: '1:434342175035:ios:9d4f961de97168a86ad71e',
    messagingSenderId: '434342175035',
    projectId: 'food-management-app-84f29',
    storageBucket: 'food-management-app-84f29.appspot.com',
    iosBundleId: 'com.example.foodManagement',
  );
}
